import { Header } from "./Header";

export default {
  title: "Components/Header",
  component: Header,
};

const Template = (args) => <Header {...args} />;

export const Default = Template.bind({});
export const EnglishAuth = Template.bind({});
export const FrenchAuth = Template.bind({});

EnglishAuth.args = {
  id: "header",
  dataGcAnalyticsCustomClickInstitutionVariable: "Institution",
  lang: "en",
  menuProps: {
    menuList: [
      { key: "dashKey", value: "My dashboard", path: "/", showIcon: false },
      { key: "profileKey", value: "Profile", path: "/", showIcon: false },
      {
        key: "securityKey",
        value: "Security settings",
        path: "/",
        showIcon: false,
      },
      {
        key: "craAccountKey",
        value: "Switch to CRA My Account",
        path: "/",
        showIcon: false,
      },
      { key: "outKey", value: "Sign out", path: "/", showIcon: true },
    ],
  },
  topnavProps: {
    skipToMainPath: "#wb-cont",
    skipToAboutPath: "#wb-info",
    switchToBasicPath: "/basic-en.html",
    displayAlternateLink: false,
  },
  breadCrumbItems: [
    { text: "Canada.ca", link: "/" },
    { text: "Link1", link: "/" },
    { text: "Link2", link: "/" },
    { text: "Max length of breadcrumb 28", link: "/" },
    { text: "Link3", link: "/" },
  ],
};

FrenchAuth.args = {
  id: "header",
  dataGcAnalyticsCustomClickInstitutionVariable: "Institution",
  lang: "fr",
  menuProps: {
    menuList: [
      {
        key: "dashKey",
        value: "Mon tableau de bord",
        path: "/",
        showIcon: false,
      },
      { key: "profileKey", value: "Profil", path: "/", showIcon: false },
      {
        key: "securityKey",
        value: "Paramètres de sécurité",
        path: "/",
        showIcon: false,
      },
      {
        key: "craAccountKey",
        value: "Aller à Mon dossier de l’ARC",
        path: "/",
        showIcon: false,
      },
      { key: "outKey", value: "Se déconnecter", path: "/", showIcon: true },
    ],
  },
  topnavProps: {
    skipToMainPath: "#wb-cont",
    skipToAboutPath: "#wb-info",
    switchToBasicPath: "/basic-fr.html",
    displayAlternateLink: false,
  },
  breadCrumbItems: [
    { text: "Canada.ca", link: "/" },
    { text: "Link1", link: "/" },
    { text: "Link2", link: "/" },
    { text: "Max length of breadcrumb 28", link: "/" },
    { text: "Link3", link: "/" },
  ],
};

Default.args = {
  globalMenuProps: {
    menuList: [
      {
        key: "jobsKey",
        value: "Jobs and the Workplace",
        path: "/",
        showIcon: false,
        itemTitle: "Jobs",
        selected: true,
        items: [
          { key: "1", value: "find a Job" },
          { key: "2", value: "Training" },
          { key: "3", value: "Hiring and managing employees" },
          { key: "4", value: "Starting a business" },
          { key: "5", value: "Workplace standards" },
          { key: "6", value: "Pensions and retirement" },
          { key: "7", value: "Employment Insurance benefits and leave" },
        ],
        mostRequested: [
          { key: "1", value: "Alpha your record of employment" },
          { key: "2", value: "Alpha for social insurance number" },
          { key: "3", value: "Alpha foreign workers" },
          { key: "4", value: "Alpha as a skilled worker" },
        ],
      },
      {
        key: "immigrationKey",
        value: "Immigration and citizenship",
        path: "/",
        itemTitle: "Immigration and citizenship",
        showIcon: false,
        selected: false,
        items: [
          { key: "1", value: "My application" },
          { key: "2", value: "Visit" },
          { key: "3", value: "Immigrate" },
          { key: "4", value: "Work" },
          { key: "5", value: "Study" },
          { key: "6", value: "Citizenship" },
          { key: "7", value: "New immigrants" },
          { key: "8", value: "Canadians" },
          { key: "9", value: "Refugees and asylum" },
          { key: "10", value: "Enforcement and violations" },
        ],
        mostRequested: [
          { key: "1", value: "Sign in or create an account to apply online" },
          { key: "2", value: "Check your application status" },
          { key: "3", value: "Check application processing times" },
          { key: "4", value: "Find an application form" },
          { key: "5", value: "Pay your fees" },
          {
            key: "6",
            value: "Find out if you need an eTA or a visa to visit Canada",
          },
          {
            key: "7",
            value: "Have questions? Find answers in the Help Centre",
          },
        ],
      },
      {
        key: "travelKey",
        value: "Travel and tourism",
        itemTitle: "Travel and tourism",
        path: "/",
        showIcon: false,
        selected: false,
        items: [
          { key: "1", value: "Travel advice and advisories" },
          { key: "2", value: "COVID-19: Travel, testing and borders" },
          { key: "3", value: "Visit Canada" },
          { key: "4", value: "Travel outside Canada" },
          { key: "5", value: "Air travel" },
          { key: "6", value: "Return to Canada" },
          { key: "7", value: "Canadian passports and travel documents" },
          { key: "8", value: "Canadian attractions, events and experiences" },
          { key: "9", value: "Assistance outside Canada" },
          { key: "10", value: "Stay connected" },
        ],
        mostRequested: [
          { key: "1", value: "Emergency assistance abroad" },
          {
            key: "2",
            value: "Find out if you need a visa to travel to Canada",
          },
          { key: "3", value: "Apply for an eTA" },
          { key: "4", value: "Apply for NEXUS" },
          { key: "5", value: "Register as a Canadian abroad" },
          { key: "6", value: "Travel insurance" },
        ],
      },
      {
        key: "businessKey",
        value: "Business and industry",
        path: "/",
        itemTitle: "Business and industry",
        showIcon: false,
        selected: false,
        items: [
          { key: "1", value: "Starting a business" },
          { key: "2", value: "Business grants and financing" },
          { key: "3", value: "Business taxes" },
          { key: "4", value: "Federal corporations" },
          { key: "5", value: "Hiring and managing employees" },
          { key: "6", value: "International trade and investment" },
          { key: "7", value: "Permits, licences and regulations" },
          { key: "8", value: "Doing business with government" },
          { key: "9", value: "R&D and innovation" },
          { key: "10", value: "Research and business intelligence" },
          { key: "11", value: "Intellectual property and copyright" },
          { key: "12", value: "Maintaining your business" },
          { key: "13", value: "Protecting your business" },
          { key: "14", value: "Insolvency for business" },
        ],
        mostRequested: [
          { key: "1", value: "Find a corporation" },
          { key: "2", value: "Report your imported goods" },
          { key: "3", value: "Search for trademarks" },
          { key: "4", value: "Review custom tariffs for importing goods" },
          { key: "5", value: "Find a patent" },
          { key: "6", value: "Import and export from Canada" },
          { key: "7", value: "Name a business" },
          {
            key: "8",
            value: "Make changes to your corporation (Online Filing Centre)",
          },
        ],
      },
      {
        key: "benefitsKey",
        value: "Benefits",
        path: "/",
        itemTitle: "Benefits",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Employment Insurance benefits and leave" },
          { key: "2", value: "Family and caregiving benefits" },
          { key: "3", value: "Public pensions" },
          { key: "4", value: "Student aid and education planning" },
          { key: "5", value: "Housing benefits" },
          { key: "6", value: "Disability benefits" },
          { key: "7", value: "Benefits by audience" },
          { key: "8", value: "Benefits payment dates" },
          { key: "9", value: "Benefits finder" },
          { key: "10", value: "Notify the government of a death" },
        ],
        mostRequested: [
          { key: "1", value: "Apply for Employment Insurance" },
          { key: "2", value: "Apply for student loans and grants" },
          {
            key: "3",
            value: "Sign in to a Government of Canada online account",
          },
          { key: "4", value: "Sign up for direct deposit" },
          { key: "5", value: "Submit your EI report" },
          { key: "6", value: "Child and family benefits calculators" },
        ],
      },
      {
        key: "healthKey",
        value: "Health",
        path: "/",
        itemTitle: "Health",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Food and nutrition" },
          { key: "2", value: "Diseases and conditions" },
          { key: "3", value: "Vaccines and immunization" },
          { key: "2", value: "Drug and health products" },
          { key: "3", value: "Product safety" },
          { key: "2", value: "Health risks and safety" },
          { key: "3", value: "Healthy living" },
          { key: "2", value: "Indigenous health" },
          { key: "3", value: "Health system and services" },
          { key: "2", value: "Science, research and data" },
        ],
        mostRequested: [
          {
            key: "1",
            value: "Licensed cultivators, processors and seller of cannabis",
          },
          { key: "2", value: "Food and product recalls and safety alerts" },
          { key: "3", value: "Canada's food guide" },
        ],
      },
      {
        key: "taxesKey",
        value: "Taxes",
        path: "/",
        itemTitle: "Taxes",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Income tax" },
          { key: "2", value: "GST/HST" },
          { key: "3", value: "Payroll" },
          { key: "4", value: "Business number" },
          { key: "5", value: "Savings and pension plans" },
          { key: "6", value: "Tax credits and benefits for individuals" },
          { key: "7", value: "Excise taxes, duties, and levies" },
          { key: "8", value: "Charities and giving" },
        ],
        mostRequested: [
          { key: "1", value: "My Account" },
          { key: "2", value: "My Business Account" },
          { key: "3", value: "Represent a Client" },
          { key: "4", value: "File a GST/HST return (NETFILE)" },
          { key: "5", value: "Make a payment to the Canada Revenue Agency" },
          { key: "6", value: "Find the next benefit payment date" },
        ],
      },
      {
        key: "environmentKey",
        value: "Environment and natural resources",
        path: "/",
        itemTitle: "Environment and natural resources",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Weather, climate and hazards" },
          { key: "2", value: "Energy" },
          { key: "3", value: "Natural resources" },
          { key: "4", value: "Agriculture and the environment" },
          { key: "5", value: "Fisheries" },
          { key: "6", value: "Wildlife, plants and species" },
          { key: "7", value: "Pollution and waste management" },
          { key: "8", value: "Environmental conservation and protection" },
        ],
        mostRequested: [
          { key: "1", value: "Local weather forecast" },
          { key: "2", value: "Fuel-efficient vehicles" },
          { key: "3", value: "Home energy efficiency" },
          { key: "4", value: "Species at risk" },
          { key: "5", value: "Prepare for severe weather" },
        ],
      },
      {
        key: "securityKey",
        value: "National security and defence",
        path: "/",
        itemTitle: "National security and defence",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "National security" },
          { key: "2", value: "Canadian Armed Forces" },
          { key: "3", value: "Defence equipment purchases and upgrades" },
          { key: "4", value: "Transportation security" },
          { key: "5", value: "Securing the border" },
          { key: "6", value: "Cyber security" },
          { key: "7", value: "Jobs in national security and defence" },
          { key: "8", value: "Services and benefits for the military" },
        ],
        mostRequested: [
          { key: "1", value: "Jobs in the Canadian Armed Forces" },
          { key: "2", value: "Military ranks" },
          { key: "3", value: "Defence equipment" },
          { key: "4", value: "Current list of terrorist entities" },
          { key: "5", value: "Join the Cadet Program" },
          { key: "6", value: "Canada's Defence policy" },
        ],
      },
      {
        key: "cultureKey",
        value: "Culture, history and sport",
        path: "/",
        itemTitle: "Culture, history and sport",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Funding - Culture, history and sport" },
          { key: "2", value: "Events, celebrations and commemorations" },
          { key: "3", value: "Cultural landmarks and attractions" },
          { key: "4", value: "Canadian identity and society" },
          { key: "5", value: "Sport" },
          { key: "6", value: "History and heritage" },
          { key: "7", value: "Arts and media" },
          { key: "8", value: "Cultural youth programs" },
          { key: "9", value: "Cultural trade and investment" },
        ],
        mostRequested: [
          { key: "1", value: "Visit the Canadian Virtual War Memorial" },
          { key: "2", value: "Anthems and symbols of Canada" },
          { key: "3", value: "Find a CRTC decision" },
          { key: "4", value: "Research your family history" },
          { key: "5", value: "Search census records" },
          { key: "6", value: "Landmarks and attractions in Canada's capital" },
        ],
      },
      {
        key: "policingKey",
        value: "Policing, justice and emergencies",
        path: "/",
        itemTitle: "Policing, justice and emergencies",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Policing" },
          { key: "2", value: "Justice" },
          { key: "3", value: "Emergencies" },
          { key: "4", value: "Corrections" },
          {
            key: "5",
            value: "Parole, record suspension, expungement and clemency",
          },
          { key: "6", value: "Victims of crime" },
        ],
        mostRequested: [
          { key: "1", value: "Apply/Renew a firearms licence" },
          { key: "2", value: "Get a criminal records check" },
          { key: "3", value: "Apply for a criminal record suspension" },
          { key: "4", value: "What to do during an emergency" },
          { key: "5", value: "Know the law on impaired driving" },
          { key: "6", value: "Help solve a crime" },
        ],
      },
      {
        key: "transportKey",
        value: "Transport and infrastructure",
        path: "/",
        itemTitle: "Transport and infrastructure",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Aviation" },
          { key: "2", value: "Marine transportation" },
          { key: "3", value: "Road transportation" },
          { key: "4", value: "Rail transportation" },
          { key: "5", value: "Dangerous goods" },
          { key: "6", value: "Infrastructure" },
        ],
        mostRequested: [
          { key: "1", value: "Zero-emission vehicles" },
          { key: "2", value: "Drone safety" },
          { key: "3", value: "What you can't bring on an airplane" },
          { key: "4", value: "Register your vessel" },
          { key: "5", value: "Child car seat safety" },
          { key: "6", value: "Transporting dangerous goods - Regulations" },
          { key: "7", value: "Canadian Aviation Regulations" },
        ],
      },
      {
        key: "worldKey",
        value: "Canada and the world",
        path: "/",
        itemTitle: "Canada and the world",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "International offices and emergency contacts" },
          { key: "2", value: "Study, work and travel worldwide" },
          { key: "3", value: "Information by countries and territories" },
          { key: "4", value: "Stories" },
          { key: "5", value: "International relations" },
          { key: "6", value: "Global issues and international assistance" },
          { key: "7", value: "Funding for international initiatives" },
          { key: "8", value: "International trade and investment" },
        ],
        mostRequested: [
          {
            key: "1",
            value: "Find a Canadian scholarship as an international student",
          },
          { key: "2", value: "International treaties signed by Canada" },
          {
            key: "3",
            value:
              "Find international study or research opportunities in Canada",
          },
          { key: "4", value: "Contact an embassy or consulate" },
          { key: "5", value: "Contact a foreign representative in Canada" },
          { key: "6", value: "Authenticate a document" },
        ],
      },
      {
        key: "moneyKey",
        value: "Money and finances",
        path: "/",
        itemTitle: "Money and finances",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Managing your money" },
          { key: "2", value: "Debt and borrowing" },
          { key: "3", value: "Savings and investments" },
          { key: "4", value: "Education funding" },
          { key: "5", value: "Pensions and retirement" },
          { key: "6", value: "Protection from frauds and scams" },
          { key: "7", value: "Financial tools and calculators" },
          { key: "8", value: "Financial literacy programs" },
          { key: "9", value: "Consumer affairs" },
          { key: "10", value: "Insolvency" },
          { key: "11", value: "Taxes" },
          { key: "12", value: "Government finances" },
          { key: "13", value: "Business grants and financing" },
          { key: "14", value: "Financial and money services regulation" },
        ],
        mostRequested: [
          { key: "1", value: "Find a bankruptcy or insolvency record" },
          { key: "2", value: "Student loans" },
          { key: "3", value: "Set up direct deposit" },
          { key: "4", value: "Mortgages" },
          { key: "5", value: "Credit report and scores" },
          { key: "6", value: "Make a budget" },
          { key: "7", value: "Rates and contribution limits" },
        ],
      },
      {
        key: "scienceKey",
        value: "Science and innovation",
        path: "/",
        itemTitle: "Science and innovation",
        showIcon: true,
        selected: false,
        items: [
          { key: "1", value: "Research funding and awards" },
          { key: "2", value: "Science subjects" },
          { key: "3", value: "Open data, statistics and archives" },
          { key: "4", value: "Research institutes and facilities" },
          { key: "5", value: "R&D and innovation" },
          { key: "6", value: "Intellectual property and copyright" },
          {
            key: "7",
            value: "Directory of scientists and research professionals",
          },
          { key: "8", value: "Science education resources" },
        ],
        mostRequested: [
          { key: "1", value: "National building codes" },
          { key: "2", value: "Official times across Canada" },
          { key: "3", value: "Check sunrise and sunset times" },
          { key: "4", value: "Grants for technological innovation (IRAP)" },
          { key: "5", value: "Federal Science Library" },
          { key: "6", value: "Live view of northern lights cam" },
        ],
      },
    ],
  },
  id: "header",
  dataGcAnalyticsCustomClickInstitutionVariable: "Institution",
  lang: "fr",
  isAuthenticated: false,
  menuProps: {
    menuList: [
      {
        key: "dashKey",
        value: "Mon tableau de bord",
        path: "/",
        showIcon: false,
      },
      { key: "profileKey", value: "Profil", path: "/", showIcon: false },
      {
        key: "securityKey",
        value: "Paramètres de sécurité",
        path: "/",
        showIcon: false,
      },
      {
        key: "craAccountKey",
        value: "Aller à Mon dossier de l’ARC",
        path: "/",
        showIcon: false,
      },
      { key: "outKey", value: "Se déconnecter", path: "/", showIcon: true },
    ],
  },
  topnavProps: {
    skipToMainPath: "#wb-cont",
    skipToAboutPath: "#wb-info",
    switchToBasicPath: "/basic-fr.html",
    displayAlternateLink: false,
  },
  breadCrumbItems: [
    { text: "Canada.ca", link: "/" },
    { text: "Link1", link: "/" },
    { text: "Link2", link: "/" },
    { text: "Max length of breadcrumb 28", link: "/" },
    { text: "Link3", link: "/" },
  ],
};
