#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

invalid_branch_regex="^(main|hotfix|release|develop|features)$"

message="This branch violates the branch naming rules. Please rename your branch."

if [[ $local_branch =~ $invalid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

# exit 0
# exec git diff-index --check --cached $against --

npm run pre-commit
