name: Build Storybook & NPM Publish
on:
  push:
    branches:
      - main
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          TARGET_FOLDER: ${{ steps.extract_branch.outputs.branch }}
          BRANCH: gh-pages # The branch the action should deploy to
          FOLDER: storybook-static # The folder the action should deploy
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - name: Publish the package
        run: npm publish --access=public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN_DTSSTN_LOCAL }}