name: Bump PR & NPM Dev Publish
on:
  pull_request:
    types: [closed]
    branches: [toronto, montreal, vancouver, winnipeg]
jobs:
  bump-pr:
      runs-on: ubuntu-latest
      if: startsWith(github.head_ref, 'release-please-') == false && github.event.pull_request.merged == true
      steps:
        - uses: google-github-actions/release-please-action@v3
          id: ga
          with:
            release-type: node
            changelog-types: '[{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"perf","section":"Performance Improvements"},{"type":"test","section":"Tests"},{"type":"docs","section":"Documentation"},{"type":"build","section":"Build System"},{"type":"ops","section":"CI/CD Changes"},{"type":"chore","section":"Miscellaneous Chores"},{"type":"refactor","section":"Refactored"}]'
            default-branch: folderx
  build-storybook:
    runs-on: ubuntu-latest
    needs: bump-pr
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-folder: folderx
          branch: gh-pages
          folder: storybook-static
          clean: true