name: Bump PR & NPM Dev Publish
on:
  pull_request:
    types: [closed, merged, opened]
    branches: [toronto, montreal, vancouver, winnipeg]
jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-folder: ${{ github.event.pull_request.head.ref }}
          branch: gh-pages
          folder: storybook-static
          clean: true